name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint and format check
        run: |
          npm run format:check
          npm run lint:css

      - name: Validate schema and i18n
        run: npm run validate

      - name: Run tests
        run: npm test

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Visual regression tests
        run: npm run test:visual

      - name: Build
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist

      - name: Upload build stats
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stats
          path: |
            stats.html
